{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.0.jar",
          "url": "gradle-plugin-1.3.0.jar",
          "size": 10595,
          "sha512": "ca761ff88bd77e5c82314b70ea07adcdc5668e24990dcfdc20df72569a460935fb3959a808cb401214287a1fa2ba5c5d155035ccd6a83a63b5b8ca605599120a",
          "sha256": "33d89b7ae39420d622f7dc339992dd530d73fd7388304a4c3198d581c1780806",
          "sha1": "2f0539387abf4bc5135cdbb91585544fc37932ed",
          "md5": "92f67fe8ad0f819a25f7f74b1ba97d25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.0.jar",
          "url": "gradle-plugin-1.3.0.jar",
          "size": 10595,
          "sha512": "ca761ff88bd77e5c82314b70ea07adcdc5668e24990dcfdc20df72569a460935fb3959a808cb401214287a1fa2ba5c5d155035ccd6a83a63b5b8ca605599120a",
          "sha256": "33d89b7ae39420d622f7dc339992dd530d73fd7388304a4c3198d581c1780806",
          "sha1": "2f0539387abf4bc5135cdbb91585544fc37932ed",
          "md5": "92f67fe8ad0f819a25f7f74b1ba97d25"
        }
      ]
    }
  ]
}
