{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.3.jar",
          "url": "gradle-plugin-1.3.3.jar",
          "size": 10629,
          "sha512": "d5124f53dd50a4b27ee1c08ef15e1078b6f1ce0a99711449fcc3df37a703b6075726124bbcce4cbefe7c143d588f72da119ef8e0f3d3e6ddb3e35d5902c47ace",
          "sha256": "dd8165d13ba02c29148062bb4d96eddc5d81c5455c5ea57f317996437380d541",
          "sha1": "aa530a9aad685d007b0e1930c567be63b3432ed8",
          "md5": "010a39f0198595ed29190253a67a38e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.3.jar",
          "url": "gradle-plugin-1.3.3.jar",
          "size": 10629,
          "sha512": "d5124f53dd50a4b27ee1c08ef15e1078b6f1ce0a99711449fcc3df37a703b6075726124bbcce4cbefe7c143d588f72da119ef8e0f3d3e6ddb3e35d5902c47ace",
          "sha256": "dd8165d13ba02c29148062bb4d96eddc5d81c5455c5ea57f317996437380d541",
          "sha1": "aa530a9aad685d007b0e1930c567be63b3432ed8",
          "md5": "010a39f0198595ed29190253a67a38e3"
        }
      ]
    }
  ]
}
