{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "610e65433132f9becc7834f0a4e5614f76fa9fc91183949497288527a9c6eaade41b32c1b1a584c16027cc313abf9058b0efbc2be30db8349872b203ee02cf3d",
          "sha256": "94120b225c5df9f4695819762bbfc898332869aa59a444037db7a48451759c59",
          "sha1": "08a0aaf4dacc61a04f8bbe4fe50fbe695d2ce8e1",
          "md5": "d0d0d1528e6002523600a7751f7dcf7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "610e65433132f9becc7834f0a4e5614f76fa9fc91183949497288527a9c6eaade41b32c1b1a584c16027cc313abf9058b0efbc2be30db8349872b203ee02cf3d",
          "sha256": "94120b225c5df9f4695819762bbfc898332869aa59a444037db7a48451759c59",
          "sha1": "08a0aaf4dacc61a04f8bbe4fe50fbe695d2ce8e1",
          "md5": "d0d0d1528e6002523600a7751f7dcf7f"
        }
      ]
    }
  ]
}
