{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "499819799e569faee59969cb12e10849b8bf6fc084358f89475a941726ef7d08fcd864065a5359e12760d56708b3e4ffca33ff904604b9d64379ac61afbb1760",
          "sha256": "8b62fe184f57a47997ca9bd1d7b337a750b2df65951ffcbb0b1e0ca8f3d0ce37",
          "sha1": "b37cb3ae849976ccdde406f706e13b440183ac8f",
          "md5": "f6b16758d057ae32ec3b8a27f3853fa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "499819799e569faee59969cb12e10849b8bf6fc084358f89475a941726ef7d08fcd864065a5359e12760d56708b3e4ffca33ff904604b9d64379ac61afbb1760",
          "sha256": "8b62fe184f57a47997ca9bd1d7b337a750b2df65951ffcbb0b1e0ca8f3d0ce37",
          "sha1": "b37cb3ae849976ccdde406f706e13b440183ac8f",
          "md5": "f6b16758d057ae32ec3b8a27f3853fa9"
        }
      ]
    }
  ]
}
