{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "2606f72953114593a0906650ee64a2b2c8d1b6dc16104a248cf92e1b1ba1ed90df690045387e8fb92e095c945ec8c1f6927f6f67509a3bf039250edfe61c8406",
          "sha256": "901ad2e1de61962c7b8aae5b4d19c95bd474136f00ec9ccd56daec6d5931b71b",
          "sha1": "33a6e5f734bddc78ff6f4c68c411547c942ca358",
          "md5": "d1be3cefefc6003fb6edfff5dff91764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.9.jar",
          "url": "gradle-plugin-1.2.9.jar",
          "size": 10595,
          "sha512": "2606f72953114593a0906650ee64a2b2c8d1b6dc16104a248cf92e1b1ba1ed90df690045387e8fb92e095c945ec8c1f6927f6f67509a3bf039250edfe61c8406",
          "sha256": "901ad2e1de61962c7b8aae5b4d19c95bd474136f00ec9ccd56daec6d5931b71b",
          "sha1": "33a6e5f734bddc78ff6f4c68c411547c942ca358",
          "md5": "d1be3cefefc6003fb6edfff5dff91764"
        }
      ]
    }
  ]
}
