package com.minthuya.sw.util

val admToCountryMap = mapOf(
    "J" to "Japan",
    "USA" to "United States",
    "ROU" to "Romania",
    "F" to "France",
    "MNG" to "Mongolia",
    "MRC" to "Morocco",
    "ISL" to "Iceland",
    "G" to "Germany",
    "POL" to "Poland",
    "ALG" to "Algeria",
    "FRO" to "Faroe Islands",
    "CHN" to "China",
    "HNG" to "Hungary",
    "KWT" to "Kuwait",
    "THA" to "Thailand",
    "UKR" to "Ukraine",
    "SVN" to "Slovenia",
    "IRN" to "Iran",
    "E" to "Spain",
    "BUL" to "Bulgaria",
    "MMR" to "Myanmar",
    "ARS" to "Argentina",
    "IND" to "India",
    "TIB" to "Tibet",
    "KOR" to "South Korea",
    "VTN" to "Vietnam",
    "AUS" to "Australia",
    "BHR" to "Bahrain",
    "KGZ" to "Kyrgyzstan",
    "KRE" to "South Korea", // Double-check context for differentiation
    "TJK" to "Tajikistan",
    "TUN" to "Tunisia",
    "CZE" to "Czech Republic",
    "LTU" to "Lithuania",
    "QAT" to "Qatar",
    "BGD" to "Bangladesh",
    "SVK" to "Slovakia",
    "GRC" to "Greece",
    "TKS" to "Turks and Caicos Islands",
    "PHL" to "Philippines",
    "HOL" to "Netherlands",
    "SYR" to "Syria",
    "UAE" to "United Arab Emirates",
    "EGY" to "Egypt",
    "ARM" to "Armenia",
    "MDA" to "Moldova",
    "CLN" to "Sri Lanka",
    "BOT" to "Botswana",
    "EST" to "Estonia",
    "TWN" to "Taiwan",
    "AFG" to "Afghanistan",
    "SWZ" to "Eswatini",
    "CYP" to "Cyprus",
    "OMA" to "Oman",
    "NOR" to "Norway",
    "DJI" to "Djibouti",
    "DNK" to "Denmark",
    "MLD" to "Maldives",
    "BEN" to "Benin",
    "BOL" to "Bolivia",
    "INS" to "Indonesia",
    "CAN" to "Canada",
    "IRL" to "Ireland",
    "VUT" to "Vanuatu",
    "D" to "Germany", // Alternative code for Germany
    "GTM" to "Guatemala",
    "UGA" to "Uganda",
    "PRU" to "Peru",
    "CUB" to "Cuba",
    "B" to "Belgium",
    "ZMB" to "Zambia",
    "GNE" to "Guinea",
    "MDG" to "Madagascar",
    "HND" to "Honduras",
    "SLM" to "Solomon Islands",
    "BEL" to "Belgium", // Alternative code for Belgium
    "UZB" to "Uzbekistan",
    "MRA" to "Mauritania",
    "CLM" to "Colombia",
    "ETH" to "Ethiopia",
    "AUT" to "Austria",
    "STP" to "São Tomé and Príncipe",
    "TUR" to "Turkey",
    "ASC" to "Ascension Island",
    "FIN" to "Finland",
    "MLI" to "Mali",
    "MEX" to "Mexico",
    "BTN" to "Bhutan",
    "EQA" to "Ecuador",
    "LBR" to "Liberia",
    "MLA" to "Malawi",
    "COG" to "Republic of the Congo",
    "SDN" to "Sudan",
    "CVA" to "Cape Verde",
    "NIG" to "Niger",
    "ALS" to "Albania",
    "NZL" to "New Zealand",
    "GUM" to "Guam",
    "GEO" to "Georgia",
    "GUI" to "Guinea",
    "PLW" to "Palau",
    "ATA" to "Antarctica"
)
