{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.1.jar",
          "url": "gradle-plugin-1.1.jar",
          "size": 10459,
          "sha512": "c42f39222a476d7793a0d7439cd9c4f28fbbf3b6df29008c75a39ceb4d667e9a7b95934924a7c7a2f10aab1efa9cb7697fc476cf69b76c836cfb0105dc0b1c12",
          "sha256": "64b32bb11f6db72c353e8773ed89e66e91ac7d0f87a1b1b70a233ff9ae15072c",
          "sha1": "6a49f0f8a03133ba22d1c62efabc59b2b2fc2617",
          "md5": "f4ea62ed91d6f96af467e57b27f2689a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.1.jar",
          "url": "gradle-plugin-1.1.jar",
          "size": 10459,
          "sha512": "c42f39222a476d7793a0d7439cd9c4f28fbbf3b6df29008c75a39ceb4d667e9a7b95934924a7c7a2f10aab1efa9cb7697fc476cf69b76c836cfb0105dc0b1c12",
          "sha256": "64b32bb11f6db72c353e8773ed89e66e91ac7d0f87a1b1b70a233ff9ae15072c",
          "sha1": "6a49f0f8a03133ba22d1c62efabc59b2b2fc2617",
          "md5": "f4ea62ed91d6f96af467e57b27f2689a"
        }
      ]
    }
  ]
}
