{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.2.jar",
          "url": "gradle-plugin-1.3.2.jar",
          "size": 10629,
          "sha512": "e7840d5aaa64fddcf28db41828af72fabaa84ad1a8d43c78accacf5f59875d2c7aea4f3a06a897d05798beccbd6816d1ef816827ebf2d22517b0ba54603936f3",
          "sha256": "34b2422da4167ae7a739eb29e308a8e06b6cc16e51a2c7579f1ed2fdf5929763",
          "sha1": "90f1a76d93d1087206b75a0955a9fb4f9f39befa",
          "md5": "50e8b23581343fa616b0b824d6fcc9fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.2.jar",
          "url": "gradle-plugin-1.3.2.jar",
          "size": 10629,
          "sha512": "e7840d5aaa64fddcf28db41828af72fabaa84ad1a8d43c78accacf5f59875d2c7aea4f3a06a897d05798beccbd6816d1ef816827ebf2d22517b0ba54603936f3",
          "sha256": "34b2422da4167ae7a739eb29e308a8e06b6cc16e51a2c7579f1ed2fdf5929763",
          "sha1": "90f1a76d93d1087206b75a0955a9fb4f9f39befa",
          "md5": "50e8b23581343fa616b0b824d6fcc9fb"
        }
      ]
    }
  ]
}
