{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.1.jar",
          "url": "gradle-plugin-1.3.1.jar",
          "size": 10629,
          "sha512": "52c880c9590a6818c82e07d046d8f4912ec4e9e4e1ce6dfe5ca8516d3788c3e53ff6d50452db1c3a97c8087b1932c7d99d845ac29874b783273b9242dd33b1d9",
          "sha256": "94c81023115ab3cd7eb549f9a2a0eee3bd4eb61bbd99ab24bd93c5a46a538a27",
          "sha1": "23e767dff3a48e35a60fa83bba31a04ac342659c",
          "md5": "59ea95a368ef49607a12682196fd9a87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.3.1.jar",
          "url": "gradle-plugin-1.3.1.jar",
          "size": 10629,
          "sha512": "52c880c9590a6818c82e07d046d8f4912ec4e9e4e1ce6dfe5ca8516d3788c3e53ff6d50452db1c3a97c8087b1932c7d99d845ac29874b783273b9242dd33b1d9",
          "sha256": "94c81023115ab3cd7eb549f9a2a0eee3bd4eb61bbd99ab24bd93c5a46a538a27",
          "sha1": "23e767dff3a48e35a60fa83bba31a04ac342659c",
          "md5": "59ea95a368ef49607a12682196fd9a87"
        }
      ]
    }
  ]
}
